/**
 * Post-build script: generates _headers with CSP hash-based script-src
 *
 * Scans all HTML files in dist/, extracts inline <script> content
 * (excluding type="application/ld+json"), computes SHA-256 hashes,
 * and writes the _headers file with proper CSP directives.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

const DIST_DIR = 'dist';

// Recursively find all HTML files
async function findHtmlFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await findHtmlFiles(fullPath));
    } else if (entry.name.endsWith('.html')) {
      files.push(fullPath);
    }
  }
  return files;
}

// Extract inline script contents from HTML (exclude ld+json and scripts with src)
function extractInlineScripts(html) {
  const scripts = [];
  // Match <script> or <script type="module"> but NOT <script type="application/ld+json"> or <script ... src="...">
  const regex = /<script(?:\s+type="module")?(?:\s[^>]*)?>([^]*?)<\/script>/gi;
  let match;
  while ((match = regex.exec(html)) !== null) {
    const tag = match[0];
    // Skip JSON-LD scripts
    if (tag.includes('type="application/ld+json"')) continue;
    // Skip scripts with src attribute (external scripts)
    if (/\bsrc\s*=/.test(tag.split('>')[0])) continue;
    // IMPORTANT : le hash CSP doit porter sur le contenu EXACT de la balise
    // (octets entre > et </script>), pas sur une version trimmée. Les navigateurs
    // hashent le textContent verbatim, whitespace de bordure compris. Pour un
    // <script is:inline> multi-lignes (loader Umami, cookie lang-switch), Astro
    // conserve l'indentation source : trimmer produit un hash qui ne matche pas
    // → script bloqué par la CSP (cas tracking Umami cassé 22/05→30/06). Les
    // scripts Astro minifiés (une ligne, sans whitespace de bordure) sont
    // inchangés par ce fix (trim = no-op sur eux).
    const content = match[1];
    if (content.trim()) {
      scripts.push(content);
    }
  }
  return scripts;
}

// Compute SHA-256 hash in CSP format
function computeHash(content) {
  const hash = createHash('sha256').update(content, 'utf-8').digest('base64');
  return `'sha256-${hash}'`;
}

async function main() {
  console.log('Scanning HTML files for inline scripts...');

  const htmlFiles = await findHtmlFiles(DIST_DIR);
  const hashSet = new Set();

  for (const file of htmlFiles) {
    const html = await readFile(file, 'utf-8');
    const scripts = extractInlineScripts(html);
    for (const script of scripts) {
      const hash = computeHash(script);
      hashSet.add(hash);
    }
  }

  const hashes = [...hashSet];
  console.log(`Found ${hashes.length} unique inline script hash(es):`);
  hashes.forEach(h => console.log(`  ${h}`));

  // Build script-src with 'self' + hashes (no unsafe-inline)
  const scriptSrc = ["'self'", ...hashes].join(' ');
  const cspValue = `default-src 'none'; script-src ${scriptSrc}; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://api.web3forms.com https://cloud.umami.is https://gateway.umami.is https://api-gateway.umami.dev; form-action 'self' https://api.web3forms.com; frame-ancestors 'none'; base-uri 'self'; manifest-src 'self'`;

  // CSP dédiée /admin (cockpit @marc/cms-engine, island React) — servie par le
  // middleware UNIQUEMENT quand pathname commence par /admin. La CSP du site
  // public ci-dessus reste STRICTEMENT inchangée. Mêmes hashes (le bootstrap
  // inline window.__cmsConfig de dist/admin/index.html est hashé comme les
  // autres), directives élargies pour le panel seulement :
  //   img-src blob: (previews upload côté client) + media-src 'self' blob: https:
  //   connect-src 'self' suffit (API /api/cms/* et /api/crm/* same-origin).
  //   frame-src https://cloud.umami.is : onglet Statistiques (iframe Umami
  //   share, cms.config → site.umamiShareUrl). Les sous-ressources de la page
  //   share sont gouvernées par la CSP d'Umami, pas par celle du parent.
  const cspAdminValue = `default-src 'none'; script-src ${scriptSrc}; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; media-src 'self' blob: https:; frame-src https://cloud.umami.is; form-action 'self'; frame-ancestors 'none'; base-uri 'self'; manifest-src 'self'`;

  // Write CSP values as JS module for the Cloudflare Pages middleware
  // (the _headers file has a 2000-char limit per header value, CSP with hashes exceeds it)
  const cspModule = `// Auto-generated by generate-csp.mjs — do not edit\nexport const CSP_VALUE = ${JSON.stringify(cspValue)};\nexport const CSP_ADMIN_VALUE = ${JSON.stringify(cspAdminValue)};\n`;
  await writeFile(join('functions', '_csp-value.js'), cspModule);
  console.log(`Generated functions/_csp-value.js (${cspValue.length} chars public + ${cspAdminValue.length} chars admin, ${hashes.length} hashes)`);

  // Static headers (CSP is handled by middleware to bypass Cloudflare _headers size limit)
  const headers = `/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=()

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/favicon.svg
  Cache-Control: public, max-age=86400

/og-*.png
  Cache-Control: public, max-age=604800

/admin
  X-Robots-Tag: noindex, nofollow

/admin/*
  X-Robots-Tag: noindex, nofollow
`;

  await writeFile(join(DIST_DIR, '_headers'), headers);
  console.log('Generated dist/_headers (without CSP)');
}

main().catch(err => {
  console.error('Error generating CSP:', err);
  process.exit(1);
});
